#pragma config(Sensor, S1,     sideSensor,     sensorSONAR)
#pragma config(Sensor, S2,     frontSensor,    sensorSONAR)
#pragma config(Sensor, S3,     rightLightSensor, sensorLightActive)
#pragma config(Sensor, S4,     leftLightSensor, sensorLightActive)
#pragma config(Motor,  motorA,          leftmotor,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightmotor,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*--------------------------------------------------------------------------------------------------------*\
|*                                                                                                        *|
|*  This program reads the light sensor and follow a line materialised by a black tape on a white floor   *|
|*                                                                                                        *|
|*                                        ROBOT CONFIGURATION                                             *|
|*                                                                                                        *|
|*    MOTORS & SENSORS:                                                                                   *|
|*    [I/O Port]              [Name]               [Type]              [Description]                      *|
|*    Port A                  leftmotor              NXT                 Left motor                       *|
|*    Port B                  rightmotor             NXT                 Right motor                      *|
|*    Port 1                  sideSensor          Sonar Sensor           side facing                      *|
|*    Port 2                  frontSensor         Sonar Sensor           front facing                     *|
|*    Port 3                  rightLightSensor    Light Sensor           floor facing                     *|
|*    Port 4                  leftLightSensor     Light Sensor           floor facing                     *|
\*--------------------------------------------------------------------------------------------------------*/

// Globular variables
int sidedistance = 0;
int frontdistance = 0;
int leftlight = 0;
int rightlight = 0;
int thresholdLight = 40;
int thresholdDiff = 10;

void displaysensors() {
	displayCenteredTextLine(0, "side distance");       /* Display side Sonar Sensor values */
	displayCenteredTextLine(1, "%d", sidedistance);   /* to LCD screen using %d.     */
	displayCenteredTextLine(2, "front distance");       /* Display front Sonar Sensor values */
	displayCenteredTextLine(3, "%d", frontdistance);   /* to LCD screen using %d.     */
	displayCenteredTextLine(4, "left light");       /* Display left Light Sensor values */
	displayCenteredTextLine(5, "%d", leftlight);   /* to LCD screen using %d.     */
	displayCenteredTextLine(6, "Light right");       /* Display right Light Sensor values */
	displayCenteredTextLine(7, "%d", rightlight);   /* to LCD screen using %d.     */
}

void readsensors() {
	sidedistance = SensorValue(sideSensor);               // Store side Sonar Sensor values in 'sonarValueSide' variable.
	frontdistance = SensorValue(frontSensor);							// Store front Sonar Sensor values in 'sonarValueFront' variable.
	leftlight = SensorValue(leftLightSensor);          // Store left Light Sensor values in 'lightValueLeft' variable.
	rightlight = SensorValue(rightLightSensor);				// Store right Light Sensor values in 'lightValueRight' variable.
	displaysensors();
}

void drive() {
	// While following a line
	while(true)
	{

		// Read light and ultrasonic sensors
		readsensors();

		//// If both light sensors detect all white (either side of the line)
		//if((leftlight > thresholdLight)&&(rightlight > thresholdLight))
		//{
		//	// Continue straight proportional to light threshold
		//	motor(leftmotor) = (leftlight - thresholdLight) * 2;
		//	motor(rightmotor) = (rightlight - thresholdLight) * 2;
		//}

		//// If line to the left of robot
		//if((leftlight < thresholdLight)&&(rightlight > thresholdLight))
		//{
		//	// Turn left
		//	motor(leftmotor) = 0;
		//	motor(rightmotor) = (rightlight - leftlight + 5) * 5;
		//}

		//// If line to the right of robot
		//if((leftlight > thresholdLight)&&(rightlight < thresholdLight))
		//{
		//	// Turn right
		//	motor(leftmotor) = (leftlight - rightlight + 5) * 5;
		//	motor(rightmotor) = 0;
		//}

		// If robot hits a black line
		if((leftlight < thresholdLight)&&(rightlight < thresholdLight))  // If the Light Sensor reads a value less than 45:
		{
			// Turn off motors and break out of loop
			motor(leftmotor) = 0;
			motor(rightmotor) = 0;
			return;
		}

		motor(leftmotor) = (leftlight - rightlight / 2 + 2) / 1.5;
		motor(rightmotor) = (rightlight - leftlight / 2 + 2) / 1.5;

	}
}

void checkDir() {

	readsensors();

	// Check if wall is NOT present left
	if(sidedistance > 18){

		playTone(500, 30);

		// Reverse a little
		motor(rightmotor) = -15;
		motor(leftmotor) = -15;
		wait1Msec(700);

		// Start turning left
		motor(rightmotor) = 3;
		motor(leftmotor) = -3;

		wait1Msec(4000);

		// Continue turning until right sensor hits the line
		int peaklight = 0;

		while(rightlight > peaklight - thresholdDiff){
			readsensors();

			if(leftlight > peaklight){
				peaklight = leftlight;
			}
		}

		// Disable motors
		motor(rightmotor) = 0;
		motor(leftmotor) = 0;


		// If no gap left, if something in front
		} else if(frontdistance < 25){

		playTone(700, 30);

		// Reverse a little
		motor(rightmotor) = -15;
		motor(leftmotor) = -15;
		wait1Msec(700);

		while(frontdistance < 25) {

			readsensors();

			// Start turning right
			motor(rightmotor) = -3;
			motor(leftmotor) = 3;

			wait1Msec(4000);

			// Continue turning until left sensor hits the line
			int peaklight = 0;

			while(leftlight > peaklight - thresholdDiff){
				readsensors();

				if(rightlight > peaklight){
					peaklight = rightlight;
				}

			}



			// Stop motors
			motor(rightmotor) = 0;
			motor(leftmotor) = 0;

		}
	}
}

task main() {

	while(true) {
		drive();

		readsensors();

		motor(rightmotor) = 15;
		motor(leftmotor) = 15;
		wait1Msec(1000);

		readsensors();

		if((leftlight < thresholdLight)&&(rightlight < thresholdLight)){
			motor(rightmotor) = 0;
			motor(leftmotor) = 0;

			playSound(soundUpwardTones);
			wait1Msec(10000);
		}

		// do readings again

		wait1Msec(500);

		checkDir();
	}

}
